[metadata]
name = "moonfly"
origin_url = "https://github.com/bluz71/vim-moonfly-colors"

[colors]
background = "#000000"
foreground = "#bdbdbd"
cursor_bg = "#9e9e9e"
cursor_fg = "#080808"
cursor_border = "#9e9e9e"
selection_bg = "#323437"
# selection_fg = "#080808"
scrollbar_thumb = "#9e9e9e"
split = "#9e9e9e"

ansi = [
  "#323437", #black (grey0)
  "#ff5454", #red
  "#8cc85f", #green
  "#e3c78a", #yellow
  "#80a0ff", #blue
  "#cf87e8", #purple (violet)
  "#79dac8", #cyan (turquoise)
  "#c6c6c6", #white
]
brights = [
  "#949494", #black (grey58)
  "#ff5189", #red (crimson)
  "#36c692", #green (emerald)
  "#c6c684", #yellow (khaki)
  "#74b2ff", #blue (sky)
  "#ae81ff", #purple
  "#85dc85", #cyan (lime)
  "#e4e4e4", #white (grey89)
]

compose_cursor = "#e3c78a"
visual_bell = "#e3c78a"
