format = """\
${custom.apple}\
${custom.linux}\
${custom.windows}\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metrics \
$all\
$character\
"""
command_timeout = 1000
add_newline = true
palette = "moonfly"

[username]
show_always = true
format = '[](bg:#1C3A5E fg:background)[  $user ](bg:#1C3A5E fg:#8DFBD2)[](fg:#1C3A5E bg:background)'

[hostname]
ssh_only = true
ssh_symbol = "󰌘 "
format = '[](bg:#88C0D0 fg:background)[$hostname ](fg:background bg:#88C0D0)[](fg:#88C0D0 bg:background)'
style = "fg:brightwhite bg:#88C0D0"

[custom.apple]
format = "[](bg:background fg:bright-cyan)[$symbol]($style)[](fg:bright-cyan bg:background)"
style = "bg:bright-cyan fg:background"
symbol = "󰀵 "
when = true
os = "macos"

[custom.linux]
format = "[](bg:background fg:bright-cyan)[$symbol]($style)[](fg:bright-cyan bg:background)"
style = "bg:bright-cyan fg:background"
symbol = " "
when = true
os = "linux"

[custom.windows]
format = "[](bg:background fg:bright-cyan)[$symbol]($style)[](fg:bright-cyan bg:background)"
style = "bg:bright-cyan fg:background"
symbol = " "
when = true
os = "windows"

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
format = '[](bg:#1C3A5E fg:background)[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)[](fg:#1C3A5E bg:background)'

[directory]
read_only = " 󰌾"
truncation_length = 0
format = "[](bg:#3B76F0 fg:background)[  $path ]($style)[](fg:#3B76F0 bg:background)"
style = "fg:brightwhite bg:#3B76F0"

[git_branch]
format = '[](bg:#FCF392 fg:background)[ $symbol$branch(:$remote_branch) ]($style)'
symbol = " "
style = "fg:#1C3A5E bg:#FCF392"

[git_status]
format = '[$ahead_behind$up_to_date $untracked$modified$staged$renamed$deleted$diverged$conflicted ]($style)[](fg:#FCF392 bg:background)'
style = "fg:#1C3A5E bg:#FCF392"
ahead = ""
behind = ""
up_to_date = ""
untracked = "?"
modified = "○"
staged = "●"
renamed = ""
deleted = ""
diverged = ""
stashed = "󰄠"

[git_metrics]
disabled = true
format = "([ $added ]($added_style))([$deleted ]($deleted_style))[](fg:#FCF392 bg:background)"
added_style = "fg:emerald bg:#FCF392"
deleted_style = "fg:red bg:#FCF392"

[character]
success_symbol = '[ 󱞩](bold green) '
error_symbol = '[ 󱞩](bold red) '

[cmd_duration]
disabled = true

[palettes.moonfly]
background = "#000000"
black = "#323437" #black (grey0)
red = "#f07496" #red
green = "#8cc85f" #green
yellow = "#e3c78a" #yellow
blue = "#80a0ff" #blue
violet = "#cf87e8" #purple (violet)
cyan = "#79dac8" #cyan (turquoise)
white = "#c6c6c6" #white
brightblack = "#949494" #black (grey58)
emerald = "#36c692" #green (emerald)
khaki = "#c6c684" #yellow (khaki)
sky = "#74b2ff" #blue (sky)
purple = "#ae81ff" #purple
lime = "#85dc85" #cyan (lime)
brightwhite = "#e4e4e4" #white (grey89)
fern = "#87d787"
lavender = "#adadf3"
orange = "#f09479"


#add all nerd font icon for programming language
[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "
format = "via [${symbol}docker]($style) "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

# [hostname]
# ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "
disabled = true

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "
disabled = true

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
disabled = true

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "


