-- local jdtls_path = require("mason-registry").get_package("jdtls"):get_install_path()
--
-- local config = {
--     cmd = {jdtls_path},
--     root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw'}, { upward = true })[1]),
-- }
-- require('jdtls').start_or_attach(config)
