# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=1000
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/yetso/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

eval "$(starship init zsh)"
eval "$(zoxide init zsh --cmd cd)"

export _ZO_RESOLVE_SYMLINKS=1
export EDITOR="nvim"
# export PATH=$PATH:$HOME/go/bin
export PROTON_ENABLE_WAYLAND=1
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# source /home/catoul/dotfiles/wezterm/wezterm.sh

alias cat='bat --theme="fly16"'
alias ls='eza --all --header --binary --color=always --group-directories-first --icons=always --no-quotes'
alias ll='eza --long --all --header --binary --color=always --group-directories-first --icons=always --no-quotes'
alias lt='eza --long --all --header --tree --level=3 --color=always --group-directories-first --icons=always --ignore-glob=".git"'
alias fastfetch='clear;command fastfetch'
alias lg='lazygit'
alias v='nvim'

function move_cursor_up {
	print -n "\e[22J"
	zle reset-prompt
}
zle -N move_cursor_up

bindkey '\e[H' beginning-of-line
bindkey '\e[F' end-of-line
bindkey '\e[3~' delete-char
bindkey '^l' move_cursor_up

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

fastfetch
